version: "3.8"

networks:
  test-net:
    driver: bridge

services:
  postgres-app:
    image: postgres:latest
    networks:
      - test-net
    restart: always
    container_name: postgres-app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
  #      - ./postgres-data:/var/lib/postgresql/data
        - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
